version: "3.8"

services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./requirements/nginx/tools/inception.crt:/etc/nginx/ssl/inception.crt
      - ./requirements/nginx/tools/inception.key:/etc/nginx/ssl/inception.key
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  mariadb:
