services:
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    networks:
      - inception
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
  ftp:
    build: ./requirements/bonus/ftp_server
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
